ALTER TABLE Branches ADD COLUMN address TEXT;
ALTER TABLE Branches ADD COLUMN phone TEXT;
ALTER TABLE Branches ADD COLUMN email TEXT;
ALTER TABLE Branches ADD COLUMN open_time TEXT;
ALTER TABLE Branches ADD COLUMN close_time TEXT;
ALTER TABLE Branches ADD COLUMN is_active INTEGER DEFAULT 1;
