name = "mellow-play-backend-api"
main = "src/index.ts"
compatibility_date = "2024-01-01"

# Production (branch: main)
[vars]
ENVIRONMENT = "production"
JWT_SECRET = "5fcf231b9b050f71452bb4d637d68a820dad6c51c88d4e3bfafc495232094d18d"

[[d1_databases]]
binding = "DB"
database_name = "mellow_play_db"
database_id = "3bdbdbe1-f307-45f9-85ea-8630660e9783"
preview_database_id = "0caad09a-1685-42f8-8f1f-668448ed38ed"

[[r2_buckets]]
binding = "BUCKET"
bucket_name = "mellow-play-assets"
preview_bucket_name = "mellow-play-assets-preview"

[[kv_namespaces]]
binding = "OTP_KV"
id = "719ca37082ed4161b640df49cf8fce3d"
preview_id = "e923d5d6ead848c88312b52bf8f79b6d"

# Development (branch: dev)
[env.dev]
name = "mellow-play-backend-api-dev"

[env.dev.vars]
ENVIRONMENT = "development"
JWT_SECRET = "5fcf231b9b050f71452bb4d637d68a820dad6c51c88d4e3bfafc495232094d18d"

[[env.dev.d1_databases]]
binding = "DB"
database_name = "mellow_play_db_dev"
database_id = "8427138f-4bd0-4ff6-8fe9-595b914d6ed8"

[[env.dev.r2_buckets]]
binding = "BUCKET"
bucket_name = "mellow-play-assets-dev"

[[env.dev.kv_namespaces]]
binding = "OTP_KV"
id = "3b85a45ec6df4e9693e7696133cccf06"
