-- Seed: แบบสอบถามความสัมพันธ์ในครอบครัว (Family Fact or Fake)
-- Guarded by the slug so re-running cannot create a second copy.

INSERT INTO Survey_Forms (name, description, form_kind, has_answer_key, is_active, slug, shuffle_questions, shuffle_options, shuffle_mode)
SELECT 'แบบสอบถามความสัมพันธ์ในครอบครัว',
       'หลังเข้าร่วมกิจกรรม Active Learning โครงการ "ครอบครัวทันโลก Family Fact or Fake"',
       'survey', 0, 1, 'family-relationship', 0, 0, 'none'
WHERE NOT EXISTS (SELECT 1 FROM Survey_Forms WHERE slug = 'family-relationship');

INSERT INTO Survey_Form_Fields (form_id, field_key, page_index, field_index, type, label, required, options_json, config_json) SELECT id, 'intro', 0, 0, 'paragraph', 'คำชี้แจง: แบบสอบถามนี้จัดทำขึ้นเพื่อสำรวจความคิดเห็นของผู้เข้าร่วมกิจกรรมเกี่ยวกับความสัมพันธ์ในครอบครัว ข้อมูลจะนำไปใช้เพื่อการประเมินและพัฒนาโครงการเท่านั้น โดยเก็บรักษาเป็นความลับและนำเสนอในภาพรวม

ไม่มีคำตอบที่ถูกหรือผิด กรุณาเลือกช่องที่ตรงกับความคิดเห็นของท่านมากที่สุด', 0, NULL, NULL FROM Survey_Forms WHERE slug = 'family-relationship';
INSERT INTO Survey_Form_Fields (form_id, field_key, page_index, field_index, type, label, required, options_json, config_json) SELECT id, 's1_head', 0, 1, 'heading', 'ส่วนที่ 1 ข้อมูลทั่วไปของผู้ตอบแบบสอบถาม', 0, NULL, NULL FROM Survey_Forms WHERE slug = 'family-relationship';
INSERT INTO Survey_Form_Fields (form_id, field_key, page_index, field_index, type, label, required, options_json, config_json) SELECT id, 's1_status', 0, 2, 'radio', 'สถานะของผู้ตอบแบบสอบถาม', 1, '[{"label":"ผู้ปกครอง (พ่อ/แม่)","points":0},{"label":"ผู้ปกครองอื่น ๆ (ปู่ ย่า ตา ยาย ฯลฯ)","points":0},{"label":"เด็กผู้เข้าร่วมกิจกรรม","points":0}]', NULL FROM Survey_Forms WHERE slug = 'family-relationship';
INSERT INTO Survey_Form_Fields (form_id, field_key, page_index, field_index, type, label, required, options_json, config_json) SELECT id, 's1_gender', 0, 3, 'radio', 'เพศ', 1, '[{"label":"ชาย","points":0},{"label":"หญิง","points":0},{"label":"ไม่ระบุ","points":0}]', NULL FROM Survey_Forms WHERE slug = 'family-relationship';
INSERT INTO Survey_Form_Fields (form_id, field_key, page_index, field_index, type, label, required, options_json, config_json) SELECT id, 's1_age', 0, 4, 'radio', 'อายุ', 1, '[{"label":"7–9 ปี","points":0},{"label":"10–15 ปี","points":0},{"label":"16–25 ปี","points":0},{"label":"26–35 ปี","points":0},{"label":"36–45 ปี","points":0},{"label":"46 ปีขึ้นไป","points":0}]', NULL FROM Survey_Forms WHERE slug = 'family-relationship';
INSERT INTO Survey_Form_Fields (form_id, field_key, page_index, field_index, type, label, required, options_json, config_json) SELECT id, 's1_members', 0, 5, 'number', 'จำนวนสมาชิกครอบครัวที่มาร่วมกิจกรรมครั้งนี้ รวมตัวท่านเอง (คน)', 1, NULL, NULL FROM Survey_Forms WHERE slug = 'family-relationship';
INSERT INTO Survey_Form_Fields (form_id, field_key, page_index, field_index, type, label, required, options_json, config_json) SELECT id, 's1_with', 0, 6, 'checkbox', 'ท่านเข้าร่วมกิจกรรมกับใคร (ตอบได้มากกว่า 1 ข้อ)', 1, '[{"label":"พ่อ/แม่","points":0},{"label":"ลูก","points":0},{"label":"ปู่ ย่า ตา ยาย","points":0},{"label":"พี่/น้อง","points":0},{"label":"อื่น ๆ","points":0,"allowText":true}]', NULL FROM Survey_Forms WHERE slug = 'family-relationship';
INSERT INTO Survey_Form_Fields (form_id, field_key, page_index, field_index, type, label, required, options_json, config_json) SELECT id, 's2_head', 1, 0, 'heading', 'ส่วนที่ 2 ความคิดเห็นเกี่ยวกับครอบครัวหลังเข้าร่วมกิจกรรม', 0, NULL, NULL FROM Survey_Forms WHERE slug = 'family-relationship';
INSERT INTO Survey_Form_Fields (form_id, field_key, page_index, field_index, type, label, required, options_json, config_json) SELECT id, 's2_note', 1, 1, 'paragraph', 'หลังเข้าร่วมกิจกรรม ท่านเห็นด้วยกับข้อความต่อไปนี้มากน้อยเพียงใด
5 = มากที่สุด · 4 = มาก · 3 = ปานกลาง · 2 = น้อย · 1 = น้อยที่สุด', 0, NULL, NULL FROM Survey_Forms WHERE slug = 'family-relationship';
INSERT INTO Survey_Form_Fields (form_id, field_key, page_index, field_index, type, label, required, options_json, config_json) SELECT id, 's2_q1', 1, 2, 'radio', 'ครอบครัวของท่านได้ร่วมกันคิดและตัดสินใจระหว่างทำกิจกรรม', 1, '[{"label":"5","points":5},{"label":"4","points":4},{"label":"3","points":3},{"label":"2","points":2},{"label":"1","points":1}]', '{"display":"scale","scored":true,"scaleLowLabel":"5 = มากที่สุด","scaleHighLabel":"1 = น้อยที่สุด"}' FROM Survey_Forms WHERE slug = 'family-relationship';
INSERT INTO Survey_Form_Fields (form_id, field_key, page_index, field_index, type, label, required, options_json, config_json) SELECT id, 's2_q2', 1, 3, 'radio', 'ท่านได้เห็นมุมมองหรือความสามารถของสมาชิกในครอบครัวเพิ่มขึ้น', 1, '[{"label":"5","points":5},{"label":"4","points":4},{"label":"3","points":3},{"label":"2","points":2},{"label":"1","points":1}]', '{"display":"scale","scored":true,"scaleLowLabel":"5 = มากที่สุด","scaleHighLabel":"1 = น้อยที่สุด"}' FROM Survey_Forms WHERE slug = 'family-relationship';
INSERT INTO Survey_Form_Fields (form_id, field_key, page_index, field_index, type, label, required, options_json, config_json) SELECT id, 's2_q3', 1, 4, 'radio', 'ท่านได้พูดคุยและรับฟังสมาชิกในครอบครัวระหว่างกิจกรรม', 1, '[{"label":"5","points":5},{"label":"4","points":4},{"label":"3","points":3},{"label":"2","points":2},{"label":"1","points":1}]', '{"display":"scale","scored":true,"scaleLowLabel":"5 = มากที่สุด","scaleHighLabel":"1 = น้อยที่สุด"}' FROM Survey_Forms WHERE slug = 'family-relationship';
INSERT INTO Survey_Form_Fields (form_id, field_key, page_index, field_index, type, label, required, options_json, config_json) SELECT id, 's2_q4', 1, 5, 'radio', 'ครอบครัวของท่านมีช่วงเวลาที่มีความสุขร่วมกันในกิจกรรมนี้', 1, '[{"label":"5","points":5},{"label":"4","points":4},{"label":"3","points":3},{"label":"2","points":2},{"label":"1","points":1}]', '{"display":"scale","scored":true,"scaleLowLabel":"5 = มากที่สุด","scaleHighLabel":"1 = น้อยที่สุด"}' FROM Survey_Forms WHERE slug = 'family-relationship';
INSERT INTO Survey_Form_Fields (form_id, field_key, page_index, field_index, type, label, required, options_json, config_json) SELECT id, 's2_q5', 1, 6, 'radio', 'กิจกรรมนี้ทำให้ครอบครัวมีหัวข้อใหม่ไว้พูดคุยกันต่อ', 1, '[{"label":"5","points":5},{"label":"4","points":4},{"label":"3","points":3},{"label":"2","points":2},{"label":"1","points":1}]', '{"display":"scale","scored":true,"scaleLowLabel":"5 = มากที่สุด","scaleHighLabel":"1 = น้อยที่สุด"}' FROM Survey_Forms WHERE slug = 'family-relationship';
INSERT INTO Survey_Form_Fields (form_id, field_key, page_index, field_index, type, label, required, options_json, config_json) SELECT id, 's2_q6', 1, 7, 'radio', 'ท่านสนใจจะทำกิจกรรมร่วมกับครอบครัวลักษณะนี้อีก', 1, '[{"label":"5","points":5},{"label":"4","points":4},{"label":"3","points":3},{"label":"2","points":2},{"label":"1","points":1}]', '{"display":"scale","scored":true,"scaleLowLabel":"5 = มากที่สุด","scaleHighLabel":"1 = น้อยที่สุด"}' FROM Survey_Forms WHERE slug = 'family-relationship';
INSERT INTO Survey_Form_Fields (form_id, field_key, page_index, field_index, type, label, required, options_json, config_json) SELECT id, 's2_q7', 1, 8, 'radio', 'รูปแบบการเล่นเป็นทีมเปิดโอกาสให้สมาชิกครอบครัวทำงานร่วมกัน', 1, '[{"label":"5","points":5},{"label":"4","points":4},{"label":"3","points":3},{"label":"2","points":2},{"label":"1","points":1}]', '{"display":"scale","scored":true,"scaleLowLabel":"5 = มากที่สุด","scaleHighLabel":"1 = น้อยที่สุด"}' FROM Survey_Forms WHERE slug = 'family-relationship';
INSERT INTO Survey_Form_Fields (form_id, field_key, page_index, field_index, type, label, required, options_json, config_json) SELECT id, 's2_q8', 1, 9, 'radio', 'โดยรวม กิจกรรมนี้ส่งผลต่อความสัมพันธ์ในครอบครัวของท่าน', 1, '[{"label":"5","points":5},{"label":"4","points":4},{"label":"3","points":3},{"label":"2","points":2},{"label":"1","points":1}]', '{"display":"scale","scored":true,"scaleLowLabel":"5 = มากที่สุด","scaleHighLabel":"1 = น้อยที่สุด"}' FROM Survey_Forms WHERE slug = 'family-relationship';
INSERT INTO Survey_Form_Fields (form_id, field_key, page_index, field_index, type, label, required, options_json, config_json) SELECT id, 's3_head', 2, 0, 'heading', 'ส่วนที่ 3 ความคิดเห็นภาพรวม', 0, NULL, NULL FROM Survey_Forms WHERE slug = 'family-relationship';
INSERT INTO Survey_Form_Fields (form_id, field_key, page_index, field_index, type, label, required, options_json, config_json) SELECT id, 's3_effect', 2, 1, 'radio', 'ท่านคิดว่าการเข้าร่วมโครงการนี้ส่งผลต่อความสัมพันธ์ในครอบครัวของท่านอย่างไร', 1, '[{"label":"ดีขึ้นมาก","points":0},{"label":"ดีขึ้น","points":0},{"label":"เหมือนเดิม","points":0},{"label":"แย่ลง","points":0}]', NULL FROM Survey_Forms WHERE slug = 'family-relationship';
INSERT INTO Survey_Form_Fields (form_id, field_key, page_index, field_index, type, label, required, options_json, config_json) SELECT id, 's3_recommend', 2, 2, 'radio', 'ท่านจะแนะนำให้ครอบครัวอื่นมาเข้าร่วมกิจกรรมลักษณะนี้หรือไม่', 1, '[{"label":"แนะนำอย่างยิ่ง","points":0},{"label":"แนะนำ","points":0},{"label":"ไม่แน่ใจ","points":0},{"label":"ไม่แนะนำ","points":0}]', NULL FROM Survey_Forms WHERE slug = 'family-relationship';
INSERT INTO Survey_Form_Fields (form_id, field_key, page_index, field_index, type, label, required, options_json, config_json) SELECT id, 's4_head', 3, 0, 'heading', 'ส่วนที่ 4 ข้อเสนอแนะเพิ่มเติม', 0, NULL, NULL FROM Survey_Forms WHERE slug = 'family-relationship';
INSERT INTO Survey_Form_Fields (form_id, field_key, page_index, field_index, type, label, required, options_json, config_json) SELECT id, 's4_impress', 3, 1, 'textarea', 'สิ่งที่ท่านประทับใจมากที่สุดจากกิจกรรมครั้งนี้', 0, NULL, NULL FROM Survey_Forms WHERE slug = 'family-relationship';
INSERT INTO Survey_Form_Fields (form_id, field_key, page_index, field_index, type, label, required, options_json, config_json) SELECT id, 's4_suggest', 3, 2, 'textarea', 'ข้อเสนอแนะเพื่อการพัฒนากิจกรรมในครั้งต่อไป', 0, NULL, NULL FROM Survey_Forms WHERE slug = 'family-relationship';
INSERT INTO Survey_Form_Fields (form_id, field_key, page_index, field_index, type, label, required, options_json, config_json) SELECT id, 's4_thanks', 3, 3, 'paragraph', 'ขอขอบพระคุณที่สละเวลาตอบแบบสอบถาม', 0, NULL, NULL FROM Survey_Forms WHERE slug = 'family-relationship';
